### ISSUE TITLE
Add .xml extension when BibXML lookups with label.

### ISSUE THREAD

**Issue by kesara** [ietf-tools/xml2rfc#1003]
### Description

For BibXML references without an extension like: 
```
<?rfc include='reference.I-D.ietf-httpbis-messaging'?>
```

add the `.xml` extension so BibXML lookup doesn't fail.

Ref: https://mailarchive.ietf.org/arch/msg/tools-discuss/QVrRuZ2HRq7pwO-ZenW9oSr3Q9A/

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cabo** [comment]
Thank you!
