### ISSUE TITLE
Add a warning when include PI (processing instructions) are used with v3

### ISSUE THREAD

**Issue by kesara** [ietf-tools/xml2rfc#1006]
### Description

`XInclude` should be used instead of ENTITY references and
XML Processing Instructions (PIs) that allow external inclusions. [1]

Add a warning when `include` PIs (`<?rfc include='<reference>' ?>`) are used with xml2rfc v3.

[1] https://datatracker.ietf.org/doc/html/rfc7991#appendix-B.1

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by reschke** [comment]
FWIW, I disagree with the part "XInclude should be used instead of ENTITY references". ENTIRY references are a standard XML feature. We should not profile XML. (And yes, the other part about warning about the PI is good).
