### ISSUE TITLE
--add-xinclude should use bib.ietf.org URLs for I-Ds

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/xml2rfc#1008]
### Description

The --add-xinclude switch creates xi:includes for RFC and I-D reference entries. However, the xi:include URLs for RFCs use bib.ietf.org, while the URLs for I-Ds use datatracker.ietf.org:
```
        <xi:include href="https://bib.ietf.org/public/rfc/bibxml/reference.RFC.7788.xml"/>
        <xi:include href="https://datatracker.ietf.org/doc/bibxml3/draft-ietf-babel-source-specific.xml"/>
```
datatracker URLs were preferred when datatracker had better BibXML information. However, it appears that BibXML contents at datatracker and bib.ietf.org are now the same. If that is the case, then the xi:include URLs that xml2rfc creates for I-Ds should use bib.ietf.org.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ajeanmahoney** [comment]
It would be nice if the flag could update any datatracker URLs in existing xi:includes to use bib.ietf.org URLs.

**Comment by kesara** [comment]
> It would be nice if the flag could update any datatracker URLs in existing xi:includes to use bib.ietf.org URLs.

@ajeanmahoney, I created #1166 for that feature request since that is a separate feature.
