### ISSUE TITLE
block quote elements are eerily asymmetric

### ISSUE THREAD

**Issue by cabo** [ietf-tools/xml2rfc#1018]
### Describe the issue

This triggers toothache for me:

<img width="463" alt="image" src="https://github.com/ietf-tools/xml2rfc/assets/23118/21ff63e5-a9f1-4e33-a18c-a2277d96083c">

Please balance the vertical blank space before and after the quote.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cabo** [comment]
(And while you are fiddling with this: do I get a pilcrow for the entire quote?)

**Comment by kesara** [comment]
> (And while you are fiddling with this: do I get a pilcrow for the entire quote?)

I created #1026 for this.
