### ISSUE TITLE
xml file that renders fine in HTML and PDF but gets error for text rendering

### ISSUE THREAD

**Issue by d3e3e3** [ietf-tools/xml2rfc#1022]
### Describe the issue

So, I have this xml v3 source file that seem to produce good HTML and PDF using the xml2rfc "IETF Author Tools" web interface. But if I ask for text output, I get the error "xml2rfc error: list index out of range". See attached:
[Sexp03-02.xml.zip](https://github.com/ietf-tools/ietf-at-ui/files/12339458/Sexp03-02.xml.zip)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
The reason for the error is `<dd>&nbsp;</dd>`. `xml2rfc` text generator is not happy that.

**Comment by d3e3e3** [comment]
Hi Kesara,

On Sun, Aug 20, 2023 at 10:21 PM Kesara Rathnayake ***@***.***>
wrote:

> The reason for the error is <dd>&nbsp;</dd>. xml2rfc text generator is
> not happy that.
>
<de> I am not surprised. I changed the draft to eliminate that and the
problem went away. Still, it seems like a bug as I don't see anything
inherently wrong with the problematic XML.

<de>Thanks,
Donald
===============================
 Donald E. Eastlake 3rd   +1-508-333-2270 (cell)
 2386 Panoramic Circle, Apopka, FL 32703 USA
 ***@***.***

**Comment by cabo** [comment]
kramdown-rfc uses `<dd><t/></dd>` to insert the empty definitions required by the, er, suboptimal grammar.
