### ISSUE TITLE
All HTML and PDF links must be hightlighted

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/xml2rfc#1058]
### Describe the issue

The effect of PR #963 on xml2rfc HTML output was discussed with the RFC Series Advisory Board (RSAB), which has determined the following:
> The RSAB confirms that RFC7993 specifies a policy that requires highlighting of links “for example, through the use of color and/or text decoration”.  ... Different handling for links that are used to link terms to a section or definition would require an update to RFC7993. Therefore all links in an RFC must be highlighted.

The details of the assessment can be found here: https://mailarchive.ietf.org/arch/msg/rsab/F9QOvdVX2amsX1bgR4DGVTzQat8/

Please roll back #963.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
Revert PR #1060 only reverts changes from PR #963.
But the figure captions still have the same issue with unhighlighted links (this has been the case for some time).
For example: https://www.rfc-editor.org/rfc/rfc9001.html#figure-1

**Comment by ajeanmahoney** [comment]
Just adding some notes here regarding the figure and table captions: 
Since the first v3 RFC (RFC 8650), both the figure label (e.g., "Figure 1") and figure caption (e.g., "TLS Layers") link to the top of the figure, but these links are only noticeable when the reader hovers a mouse cursor over them. There is some documentation in [Implementation notes for RFC7991](https://datatracker.ietf.org/doc/html/draft-levkowetz-xml2rfc-v3-implementation-notes#name-in-section-925-figure) regarding the figure caption. Table labels and captions work the same way. 

The [accessibility spot check report](https://drive.google.com/file/d/1F3TkU3HJhrJTLTty7-zqoa0emtHL2ueb/view?pli=1) mentions these double links (label and caption), and says the following:

> If it is important to allow users to share the diagram using the fragment URL then use
only one link to encompass the caption text and ensure that the link targets the
`<figure>` container.

>Note that users may achieve a similar outcome by using the permalink for the section
heading. If this feature is sufficient, the link mark-up can be removed from both text
elements in the caption.

Maybe the visibility of label and caption links should be a separate issue.
