### ISSUE TITLE
Failing on MacOS 10.15.7

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-tools/xml2rfc#1059]
### Describe the issue

I know 10.15.7 is an old version of MacOS, but I was successfully building my I-d a few months ago. I don't think it was anything that I changed on my system. Now that the area director has finished review of my draft, I can't build it.

The trouble seems to be with lxml. Maybe lxml no longer supports MacOS 10.15.7? See below.

I have tried to install lxml directly, but that seems complicated.

Appreciate any ideas you might have, but understand that there may be nothing possible for you to do.

Thank you kindly,

LL

(I find all the auto-install that happens here very frightening because I have no control to prevent breakage like this and debugging this could take days)

Building wheels for collected packages: lxml
  Building wheel for lxml (setup.py) ... error
   ...
xcrun -sdk macosx clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -DCYTHON_CLINE_IN_TRACEBACK=0 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Isrc -Isrc/lxml/includes -I/Users/lgl/IETF/EAT/eat-drafts/9393/lib/.venv/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/lxml/etree.c -o build/temp.macosx-10.14.6-x86_64-cpython-38/src/lxml/etree.o -w -flat_namespace
      In file included from src/lxml/etree.c:96:
      In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:11:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/limits.h:63:
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
If you use homebrew or macports, try reinstalling or upgrading Python.

BTW, a quick search for that error suggested trying `ARCHFLAGS="-arch x86_64" pip3 install xml2rfc` (provided that you don't have an M1/2 (ARM) machine). See https://stackoverflow.com/a/67715297

**Comment by laurencelundblade** [comment]
I upgraded MacOS and am OK now.
