### ISSUE TITLE
Tables in <dd> tags do not render desired html output

### ISSUE THREAD

**Issue by mchurch-rpc** [ietf-tools/xml2rfc#1086]
### Describe the issue

In the html output, tables within `<dd>` tags start on the same line as a term within `<dt>` tags. In the txt output, these tables start on the next line. The pdf output varies - sometimes the table is on the same line as the term within `<dt>` tags and sometimes it is on the next line.

The table should start on the next line in all three outputs (like in the txt output).

For examples, please see Tables 1-35 in the files below. For the pdf output, the table appears on the next line (like the txt output) in all except Tables 7, 14, 17, 18, 19, and 28.

https://www.rfc-editor.org/v3test/draft-ietf-cellar-matroska-21.html
https://www.rfc-editor.org/v3test/draft-ietf-cellar-matroska-21.txt
https://www.rfc-editor.org/v3test/draft-ietf-cellar-matroska-21.pdf
https://www.rfc-editor.org/v3test/draft-ietf-cellar-matroska-21.xml

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
In the `dl` element, the `newline` attribute can be set to `True` to move the definition (`table` in this case) to the next line. [^1]

> The table should start on the next line in all three outputs (like in the txt output).

I think it should be the other way around. The text output is not rendering correctly because `newline` is not set?

[^1]: https://ietf-tools.github.io/xml2rfc/#name-newline-attribute-new

**Comment by ajeanmahoney** [comment]
@kesara, the RPC will work on how we want the inclusion of a table within a definition list to look for all list formats (true/false newline, normal/compact spacing) and will open a new issue, thanks!
