### ISSUE TITLE
Format of a subseries reference that contains a single RFC

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/xml2rfc#1095]
### Describe the issue

(including @cabo because he opened #1067)

While the fix for #1067 looks good for multiple-RFC subseries references, the references for subseries that contain only one RFC look odd because two URLs are included for a single document. 

Previous:
```
   [STD72]    Gellens, R. and J. Klensin, "Message Submission for Mail",
              STD 72, RFC 6409, November 2011.

              <https://www.rfc-editor.org/info/std72>
```
Current:
```
   [STD72]    Gellens, R. and J. Klensin, "Message Submission for Mail",
              STD 72, RFC 6409, DOI 10.17487/RFC6409, November 2011,
              <https://www.rfc-editor.org/info/rfc6409>.

              <https://www.rfc-editor.org/info/std72>
```
New:
```
   [STD72]    Gellens, R. and J. Klensin, "Message Submission for Mail",
              STD 72, RFC 6409, DOI 10.17487/RFC6409, November 2011,
              <https://www.rfc-editor.org/info/std72>.
``` 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cabo** [comment]
> references for subseries that contain only one RFC look odd because two URLs are included for a single document.

The link for the document is included with the document.

The problem is that the link for the subseries entry is unadorned (and at the wrong end).
This is a problem for both the single-document entry and the multi-document entry.

I'm sure we can tweak this some more; my objective was to first no longer lose information (and to stop making Internet Standard documents second class citizens as they no longer get a link).

**Comment by cabo** [comment]
(You can always tweak the XML to say what you want to have; you don't need a referencegroup for your example.
I'd rather keep the referencegroup though.)

**Comment by cabo** [comment]
Generally speaking, having information in the XML that the renderer then chooses to delete in some of the renderings just because of some style consideration is a non-starter.

**Comment by cabo** [comment]
Example for better rendering:

```
[STD72]       Internet Standard 72, <https://www.rfc-editor.org/info/std72>.
              At the time of writing, this comprises the following document:

              Gellens, R. and J. Klensin, "Message Submission for Mail",
              STD 72, RFC 6409, DOI 10.17487/RFC6409, November 2011,
              <https://www.rfc-editor.org/info/rfc6409>.
```

This actually explains the unfamiliar STD/BCP abbreviation and indicates that the composition of the subseries entry can change over time (e.g., STD96).

**Comment by ajeanmahoney** [comment]
@cabo I like your suggestion and the RPC has been discussing it, thanks!

**Comment by ajeanmahoney** [comment]
Note that the RPC will open a new issue that will describe the format of subseries references for both the one-rfc and multi-rfc cases.
