### ISSUE TITLE
Please roll back the fix to #1067

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/xml2rfc#1097]
### Describe the issue

While the RPC is working on the details of the style of subseries references, please roll back the fix to #1067 so that there's not a mix of subseries ref styles. 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cabo** [comment]
You still seem to be relying on xml2rfc deciding which parts of the XML to render.  This is broken.  You need to set the XML to include what you want to render.  xml2rfc needs to render the XML.
