### ISSUE TITLE
Updated format for subseries references 

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/xml2rfc#1100]
### Description

Please add introductory text to the subseries reference that captures the "name" of the subseries: "Internet Standard NN", "Best Current Practice NN", or "For Your Information NN", and provide a link to the subseries info page.  Add the text "At the time of writing, this [STD|BCP|FYI] comprises the following:" as a lead-in to the list of RFCs within the subseries.  

For the RFCs listed within the subseries, please provide each RFC's DOI and info URL as is currently done for individual RFC references. 

An example of a single-RFC subseries reference in this requested format:
```
   [STD72]    Internet Standard 72,
              <https://www.rfc-editor.org/info/std/std72>.
              At the time of writing, this STD comprises the following:

              Gellens, R. and J. Klensin, "Message Submission for Mail",
              STD 72, RFC 6409, DOI 10.17487/RFC6409, November 2011,
              <https://www.rfc-editor.org/info/rfc6409>.
```

An example of a multiple-RFC subseries reference in this requested format:
```
   [STD69]    Internet Standard 69, 
              <https://www.rfc-editor.org/info/std69>.
              At the time of writing, this STD comprises the following:

              Hollenbeck, S., "Extensible Provisioning Protocol (EPP)",
              STD 69, RFC 5730, DOI 10.17487/RFC5730, August 2009,
              <https://www.rfc-editor.org/info/rfc5730>.

              Hollenbeck, S., "Extensible Provisioning Protocol (EPP)
              Domain Name Mapping", STD 69, RFC 5731, 
              DOI 10.17487/RFC5731, August 2009,
              <https://www.rfc-editor.org/info/rfc5731>.

              Hollenbeck, S., "Extensible Provisioning Protocol (EPP)
              Host Mapping", STD 69, RFC 5732, DOI 10.17487/RFC5732, 
              August 2009, 
              <https://www.rfc-editor.org/info/rfc5732>.

              Hollenbeck, S., "Extensible Provisioning Protocol (EPP)
              Contact Mapping", STD 69, RFC 5733, 
              DOI 10.17487/RFC5733, August 2009, 
              <https://www.rfc-editor.org/info/rfc5733>.

              Hollenbeck, S., "Extensible Provisioning Protocol (EPP)
              Transport over TCP", STD 69, RFC 5734, 
              DOI 10.17487/RFC5734, August 2009, 
              <https://www.rfc-editor.org/info/rfc5734>.
```
Requested intro for a BCP:
```
   [BCP14]    Best Current Practice 14, 
              <https://www.rfc-editor.org/info/bcp14>.
              At the time of writing, this BCP comprises the following:
              ....
```
Requested intro for an FYI:
```
   [FYI28]    For Your Information 28, 
              <https://www.rfc-editor.org/info/fyi28>.
              At the time of writing, this FYI comprises the following:
              ....
```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ajeanmahoney** [comment]
@cabo because he started the ball rolling with #1067

**Comment by ajeanmahoney** [comment]
A note on the [FYI subseries](https://www.rfc-editor.org/search/rfc_search_detail.php?page=All&rfc=FYI&pubstatus[]=Any&pub_date_type=any&sortkey=Number&sorting=ASC) -- this subseries was concluded with [RFC 6360](https://www.rfc-editor.org/rfc/rfc6360.html) and is not expected to be revived.

**Comment by ajeanmahoney** [comment]
The RPC believes this feature request is fully specified and can move forward.  The FYI subseries is included so that all subseries will be treated consistently by the tools.

**Comment by kesara** [comment]
The `target` attribute for `referencegroup` is optional.
What is the expected output when `target` is not present?

**Comment by kesara** [comment]
See examples for new presentations at https://github.com/ietf-tools/xml2rfc/pull/1102#issue-2133697366

**Comment by ajeanmahoney** [comment]
> The target attribute for referencegroup is optional.
> What is the expected output when target is not present?

For RFC references, xml2rfc currently provides a URL in the output if the target attribute is empty. Can the same be done here? (Although I hope that authors use xi:includes for subseries references to reduce errors).

**Comment by kesara** [comment]
@ajeanmahoney https://github.com/ietf-tools/xml2rfc/pull/1102/commits/205c09c84fb4f204d727ae64c56dab70d61fe768 adds this features.

Examples:
| Format | Example |
| --- | --- |
| XML | [draft-foobar-00.xml](https://t4.fq.nz/subseries-reference-targets/draft-foobar-00.xml) |
| Text | [draft-foobar-00.txt](https://t4.fq.nz/subseries-reference-targets/draft-foobar-00.txt) |
| HTML | [draft-foobar-00.html](https://t4.fq.nz/subseries-reference-targets/draft-foobar-00.html) |
| PDF | [draft-foobar-00.pdf](https://t4.fq.nz/subseries-reference-targets/draft-foobar-00.pdf) |
