### ISSUE TITLE
Missing whitespace in txt output after table in `<dd>`

### ISSUE THREAD

**Issue by rvanrheenen** [ietf-tools/xml2rfc#1118]
### Describe the issue

In the txt output, when a `<dl>` with spacing=“compact” includes `<table>` in `<dd>`, there is no space between the table title and next `<dd>`.

For example, for Table 5 in the txt output (see files below), there should be a blank line between the table title and "stream copy:  True (Section 8)". For additional examples, see Tables 3, 6, 7, and 8 in the txt output. 

There is space after the table title in the pdf and html outputs; the missing space only occurs in the txt output.

Files:
https://www.rfc-editor.org/v3test/rfc9559-TEST.xml
https://www.rfc-editor.org/v3test/rfc9559-TEST.txt
https://www.rfc-editor.org/v3test/rfc9559-TEST.html
https://www.rfc-editor.org/v3test/rfc9559-TEST.pdf

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rvanrheenen** [comment]
Also see #1117 and #1086 (other issues re `<table>` in `<dl>` found in same document)

**Comment by kesara** [comment]
Because `spacing="compact"` shouldn't HTML/PDF tables lose the space after the table?
In text output, the blank line between the table and the table caption should be removed?

**Comment by ajeanmahoney** [comment]
@kesara, the RPC will work on how we want the inclusion of a table within a definition list to look for all list formats (true/false newline, normal/compact spacing) and will open a new issue, thanks!
