### ISSUE TITLE
xml2rfc adding a space after the slash and hyphen characters in the name attribute

### ISSUE THREAD

**Issue by mferguson-rpc** [ietf-tools/xml2rfc#1126]
### Describe the issue

We are getting added space following the hyphen and slash characters in the name attribute (not line-break related).  We are using &wj; as a workaround.  Examples below:

In RFC 9244 (Figure 48):

Input:
`<name>GET Request to Receive Asynchronous Notifications Filtered Using Uri-Query</name>`

Output:
`Figure 48: GET Request to Receive Asynchronous Notifications Filtered Using Uri- Query`

In RFC 9486 (Figure 1):

Input:
`<name>IPv6 Hop-by-Hop and Destination Option Format for Carrying IOAM Data-Fields</name>`

Output:
`        Figure 1: IPv6 Hop-by-Hop and Destination Option Format for
                         Carrying IOAM Data- Fields`

In draft-ietf-alto-new-transport-22 (Figure 6):

Input:
` <name>Example of an ALTO Server Supporting the ALTO Base Protocol, ALTO/SSE, and ALTO TIPS</name>`

Output:
 `Figure 6: Example of an ALTO Server Supporting the ALTO Base
                     Protocol, ALTO/ SSE, and ALTO TIPS`

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
Seems like a duplicate of #961?

**Comment by mferguson-rpc** [comment]
Yes - just adding the slash character I guess.  Sorry for the noise!
