### ISSUE TITLE
Synthesized References Section does not get an anchor assigned

### ISSUE THREAD

**Issue by cabo** [ietf-tools/xml2rfc#1133]
### Describe the issue

xml2rfc sometimes synthesizes a References section around the informative and normative References sections.
This section does not receive an anchor, so it cannot be referenced in an <xref

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cabo** [comment]
It appears that this is done in `element_back` in v2v3.py

**Comment by kesara** [comment]
@cabo, Do you have an example? Thanks.

**Comment by kesara** [comment]
@cabo, Are you referring to the lack of an `anchor` attribute in the `<references>` tag just after the `<back>` tag?

The `anchor` is an optional attribute for `<references>`. So, I think it's okay to skip adding an artificial `anchor`.


For historical reasons, v2v3 converter encapsulates all `<references>` into a single `<references>` [^1].

[^1]: https://github.com/ietf-tools/xml2rfc/blob/main/xml2rfc/writers/v2v3.py#L478C1-L480C61

**Comment by cabo** [comment]
Well, the XML generated is valid; it just leads to text like the below:

https://cbor-wg.github.io/edn-literal/close-42/draft-ietf-cbor-edn-literals.html#name-structure-of-this-document

There is no way to reference Section 6, so the text separately references Section 6.1 and 6.2.

If the v2v3 behavior to synthesize a top-level References section is here to stay, I could simply preempt that behavior in kramdown-rfc and apply an anchor there.

**Comment by kesara** [comment]
I don't know the reason why v2v3 encapsulates multiple `<references>` into single `<references>`.
But I would assume it would be an undesirable change now since the `xml2rfc` v2v3 converter has behaved that way for many years, so better to preempt that behavior in `kramdown-rfc`?

**Comment by cabo** [comment]
Done in https://github.com/cabo/kramdown-rfc/commit/98ff1bd

(I'm not going to make a new release now right before the I-D deadline, so this will be in 1.8.1 on July 9)

**Comment by cabo** [comment]
Thanks for the feedback!
