### ISSUE TITLE
Superscripts and the light height in PDF output

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/xml2rfc#1160]
### Describe the issue

When the first line of an unordered list contains a superscript, the bullets are placed higher in the PDF output. For example, the bullets for the list in Section 3.1 of RFC 9616 are higher than the ones in Section 4 in the PDF. The bullet heights are fine in the HTML output. 

https://www.rfc-editor.org/rfc/rfc9616.pdf

If the list has superscripts but they are not in the first bullet item, then the placement of the bullets is okay. For example, See Section 5.2.1 of RFC 9429. 

https://www.rfc-editor.org/rfc/rfc9429.pdf

The RPC does not consider this a blocking issue. 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
This seems to be an WeasyPrint issue. See https://github.com/Kozea/WeasyPrint/issues/2253

**Comment by kesara** [comment]
List items with subscript in firs line in an ordered list will suffer from the same issue.

**Comment by kesara** [comment]
The proposed fix (#1165) generates the following output:
Note that this also fixes line height weirdness when the subscript is in one of the middle lines.

### Section 3.1 of RFC 9616 
<img width="898" alt="Screenshot 2024-09-18 at 23 06 42" src="https://github.com/user-attachments/assets/2533c57b-d32b-46dc-a2e9-0ffbaf680b56">

### Section 5.2.1 of RFC 9429
<img width="852" alt="Screenshot 2024-09-18 at 23 07 33" src="https://github.com/user-attachments/assets/79201d12-7279-4bda-8a9f-82e369ebe9cb">

**Comment by kesara** [comment]
Maybe the line height should be set to `0` for the whole document not just `li` elements.
See Section Section 4.1 in RFC9591:
<img width="810" alt="Screenshot 2024-09-18 at 23 12 46" src="https://github.com/user-attachments/assets/9ceed9bc-7ee0-4615-b7d9-8b626863dbb9">

There is a line height issue when `sup` elements are present.

**Comment by ajeanmahoney** [comment]
I'm good with proposed fix (https://github.com/ietf-tools/xml2rfc/pull/1165)
