### ISSUE TITLE
Capitalize "SVG" in "Artwork only available as svg"

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/xml2rfc#1169]
### Description

Thanks for #1140! Please capitalize "SVG" in the output.

Current:
```(Artwork only available as svg: see https://www...```

Requested:
```(Artwork only available as SVG: see https://www...```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
If the artwork type is unknown, the string will be `Artwork only available as (unknown type): https://`.

**Comment by kesara** [comment]
In `xml2rfc` artwork `type` is a free string [^1].
The proposed change will capitalize any string in that `type` attribute.

[^1]: https://ietf-tools.github.io/xml2rfc/#section-2.6.7
