### ISSUE TITLE
misleading warning for sparse postal information

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#385]
`type_enhancement`   |    by julian.reschke@gmx.de

___

In the attached example, one author has only city and country specified. The warning is:

```
foo.xml(28): Warning: Address check failed for author Πυθαγόρας ὁ Σάμιος.
foo.xml(28):    Unexpected address info: <code>: (empty)
foo.xml(28):    Unexpected address info: <street>: (empty)
foo.xml(28): Note: Recognized address elements for Greece are: <extaddr>, <street>, <code>, <city>, <country>
```

So something seems to insert the empty elements causing the warning message.

___
_Issue migrated from trac:385 at 2022-02-05 12:47:05 +0000_

**Comment by kesara** [comment]
OBE (v2).
