### ISSUE TITLE
misleading warnings when <postalLine> is used

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#386]
`type_enhancement`   |    by julian.reschke@gmx.de

___

In the attached example, one author's address is specified using <postalLine> only.

This generates the following warning:

```
Warning: Did not find a recognized country entry for author Julian Reschke
```

___
_Issue migrated from trac:386 at 2022-02-05 12:47:09 +0000_

**Comment by kesara** [comment]
OBE
