### ISSUE TITLE
warning on <extaddr>

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#388]
`type_defect`   |    by miek@miek.nl

___

Version: 2.15.2

When compiling an example RFC (https://raw.githubusercontent.com/mmarkdown/mmark/master/rfc/7511.md) I get the warning:
```
7511.xml(7): Note: Recognized postal address elements for Germany are: <extaddr>, <street>, <code>, <city>, <country>
```
But I don't think `<extaddr>` exists.

___
_Issue migrated from trac:388 at 2022-02-05 12:47:17 +0000_

**Comment by kesara** [comment]
OBE
