### ISSUE TITLE
preptool inserts section with author names

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#460]
`type_defect`   |    by julian.reschke@gmx.de

___

The preptool mode inserts a back section containing author elements, apparently to give <xref>'s in the generated boilerplate/toc something to link to.

There are multiple issues with that:

- it violates the DRY principle
- it is not documented anywhere
- the inserted section is indistinguishable from a regular section - how is a formatter supposed to know when to process it?
- it adds <author> to the content model of <section>

(tested with 2.35, but there's no "Version" configured here for that)

(see also <https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/81> which discusses hiw to style *contributors* sections)

___
_Issue migrated from trac:460 at 2022-02-08 07:03:54 +0000_

**Comment by kesara** [comment]
Closing as per https://github.com/ietf-tools/xml2rfc/issues/460#issuecomment-1032275509
