### ISSUE TITLE
improved placement of page breaks in the PDF

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#463]
`owner:henrik@levkowetz.com` `type_enhancement`   |    by arusso@amsl.com

___

Hoping for automatic prevention of

a) page break between reference tag and reference entry
ex: p. 12-13 of https://www.rfc-editor.org/rfc/rfc8689.pdf
p. 12-13 of https://www.rfc-editor.org/authors/rfc8663.pdf

b) page break after section title
ex: section 4 (p. 13-14) of https://www.rfc-editor.org/authors/rfc8695.pdf

___
_Issue migrated from trac:463 at 2022-02-08 07:04:07 +0000_

**Comment by kesara** [comment]
Examples of the original issue seem to have gone away.

**Comment by kesara** [comment]
The following issues have gone away:
* https://github.com/ietf-tools/xml2rfc/issues/463#issuecomment-1032275700
* https://github.com/ietf-tools/xml2rfc/issues/463#issuecomment-1032275699
* https://github.com/ietf-tools/xml2rfc/issues/463#issuecomment-1032275707

I this this is a still an issue:
* https://github.com/ietf-tools/xml2rfc/issues/463#issuecomment-1032275706

**Comment by kesara** [comment]
I've created #1119 in https://github.com/ietf-tools/xml2rfc/issues/463#issuecomment-1032275706 because it's a bit different to the other page break issues.

Other issues mentioned here seem OBE.
Please comment if that's not the case.
