### ISSUE TITLE
table cells have different background in PDF vs. HTML when using rowspan

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#468]
`owner:henrik@levkowetz.com` `type_defect`   |    by arusso@amsl.com

___

In the PDF, it seems the gray background of a cell (where rowspan is used) should fill the whole cell, i.e., should extend vertically downward, as it does in the HTML.

Compare Table 6 in
HTML (https://www.rfc-editor.org/authors/rfc8697.html#section-7.5)
vs.
PDF (https://www.rfc-editor.org/authors/rfc8697.pdf)

source: https://www.rfc-editor.org/authors/rfc8697.xml

(see the cells that contain "26" and "Association Error".)

Same issue in Table 1 of this document (the cells that contain "40" and "ASSOCIATION").  

___
_Issue migrated from trac:468 at 2022-02-08 07:04:29 +0000_

**Comment by rjsparks** [comment]
@kesara - See if this can come out of waiting?

**Comment by kesara** [comment]
This issue is OBE.
<img width="885" alt="Screenshot 2024-03-27 at 18 10 18" src="https://github.com/ietf-tools/xml2rfc/assets/1027692/32e8fa3c-3ceb-4325-939a-7e920d87635a">
