### ISSUE TITLE
nit in PDF running header

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#500]
`type_defect`   |    by arusso@amsl.com

___

See running header (top of page 2). Line break between the month and year. (Typical output is one line.)

In https://www.rfc-editor.org/v3test/runningheader-test.pdf
```
March
2020
```

In https://www.rfc-editor.org/v3test/runningheader-test2.pdf
```
April
2020
```

input files:
https://www.rfc-editor.org/v3test/runningheader-test.xml
https://www.rfc-editor.org/v3test/runningheader-test2.xml
https://www.rfc-editor.org/v3test/draft-ietf-teas-yang-te-types-13.original.v2v3.xml
We've only seen this with this one draft (and the truncated copies of it posted above).

___
_Issue migrated from trac:500 at 2022-02-08 07:06:41 +0000_

**Comment by kesara** [comment]
@alicerusso Closing this as this can not be reproduced.
Reopen if this is still an issue.
