### ISSUE TITLE
bibtex library: reference.RFC.1425.xml - apparent messed-up conversion

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#502]
`type_defect`   |    by john-ietf@jck.com

___

Apparently, when the author information for RFC 1425 was converted to XML and then stored in the library, what should have become:

<author initials="J." surname="Klensin" fullname="J. Klensin" role="WG Chair">
<organization/>
</author>

was converted into 

<author initials="J." surname="Klensin" fullname="J. Klensin">
<organization/>
</author>
<author initials="WG" surname="Chair" fullname="WG Chair" role="WG Chair">
<organization/>
</author>

However, that isn't going to work either because, according to my copy of the revised rfc2629.dtd and my reading of RFC 7749, the only valid value for the "role" attribute is "editor".

Given that we cannot change older RFCs and that roles like that occasionally appear (that one was carried forward into 1651 and 1869, and I vaguely remember some others), this may imply a need for an addition to the xml2rfc vocabulary, even if its use is then deprecated by the IESG.

In any event, the bibxml entry should be adjusted sufficiently that it does not produce a fatal error in xml2rfc.

I can work around this, so a fix is not urgent

___
_Issue migrated from trac:502 at 2022-02-08 07:06:49 +0000_

**Comment by kesara** [comment]
OBE
