### ISSUE TITLE
line break within a word in text output

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#532]
`resolution_duplicate` `type_defect`   |    by arusso@amsl.com

___

There's a line break in the word "feature" in this <dd> (after a very long <dt>).

output:
```
   The feature tag is intended primarily for use in the following
   applications, protocols, services, or negotiation mechanisms:  This f
      eature tag is most useful in a communications application for
      describing the capabilities of a device to use the CLUE control
      protocol to negotiate the use of multiple media streams.
```

Files:
https://www.rfc-editor.org/v3test/line_break_inside_a_word.xml
https://www.rfc-editor.org/v3test/line_break_inside_a_word.txt
(see Section 10.2)

Workaround: insert <br/> to get a line break after the colon. We wouldn't use newline="true" bc of replicating the original format of the rest of the list items. (Even if the "f" break shown above weren't happening, the <br/> gives the desired output, so "This" is not by itself.)

___
_Issue migrated from trac:532 at 2022-02-08 07:08:43 +0000_

**Comment by alicerusso** [comment]
This seems to be the same issue as #857 

In some cases, the workaround (changing the `<dl>` to newline="true") is not desired.
