### ISSUE TITLE
t elements under dd elements

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#538]
`type_defect`   |    by martin.thomson@gmail.com

___

This is clearly permitted by RFC 7991, but the tool rejects these:

```
Error: Element dd has extra content: t, at /rfc/middle/section49521fd0424a83579db2451037cce9850447f337/section5f1f8b9ced72dea365b98717219bbeadc86cce74/dl/dd5f1f8b9ced72dea365b98717219bbeadc86cce74/t5f1f8b9ced72dea365b98717219bbeadc86cce74
```

___
_Issue migrated from trac:538 at 2022-02-08 07:09:07 +0000_

**Comment by martinthomson** [comment]
I'm unable to reproduce now and have lost the original context.  Perhaps it is best to close this issue now.
