### ISSUE TITLE
XML2RFC Internal Error

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#555]
`type_defect`   |    by jason_livingood@comcast.com

___

Seeing this error in uploading XML to generate an I-D. I am using a file that worked yesterday with no issues. 

 Unable to Convert File Exit with code 1 due to http error: 1203 
Apache/2.2.22 (Debian) Server at xml2rfc.tools.ietf.org Port 443 durif

___
_Issue migrated from trac:555 at 2022-02-08 07:10:07 +0000_

**Comment by kesara** [comment]
OBE
