### ISSUE TITLE
biblxml library runaround, especially on old RFCs

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#562]
`type_defect`   |    by john-ietf@jck.com

___

First of all, it is nowhere obvious as to whether RFC 20 is in the libraries as "RFC.20" or "RFC.0020".  I note that reasonable references use t he former form and that, if the libraries (or the RFC Editor) decide to insist on the latter, everything (including XML for older I-Ds) is going to need to be redone.  Noting only one month between 8900 and 8940 and only three months since RFC 8800, that may not be very far off.

Whatever the convention is going to be, it should probably be clear on the xml2rfc home page or somewhere what else obvious what it is to avoid trying to incrementally learn from obscure error messages.

More generally...

I tried to compile a xml2rfc v2 document today that references some very old RFCs, e.g., RFC 20, via an entity statement that read:

<!ENTITY rfc20 PUBLIC '' "http://xml.resource.org/public/rfc/bibxml/reference.RFC.20.xml">

Can't be processed.  Attempting to retrieve through that link bets me a message that says

Moved Permanently
The document has moved here, pointing to
https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.20.xml

Using that link gets a "not found" error.

So, experimenting with conventions, I try to retrieve
https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.0020.xml
which produces the expected file.   Good news.

However, if one looks at the "Citation Libraries" section of https://xml2rfc.tools.ietf.org/, it claims these RFC citations are at 
http://xml2rfc.ietf.org/public/rfc/bibxml/ (even though the link under that reference is to
https://xml2rfc.tools.ietf.org/public/rfc/bibxml/ ).  If one actually tries to use http://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.0020.xml
one again gets a 301 erros pointing back to xml2rfc.tools.ietf.org.

The examples under "Including files" also uses http://xml2rfc.ietf.org/public/rfc/bibxml/...

This is, IMnvHO, wildly confusing, unnecessary, and a considerable waste of the user's time.  If, for some reason, we can't have these other locations just quietly redirect, can we at least get our stories straight as to where these files actually are?  It seems to that something equivalent to
  <a href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/"
     http://xml2rfc.ietf.org/public/rfc/bibxml/ > 
is especially bad practice, if only because references like
  <a href="https://evildoer.example/login" https://goodguys.example/login > 
is a favorite trick of the phishing community.

___
_Issue migrated from trac:562 at 2022-02-08 07:10:37 +0000_

**Comment by kesara** [comment]
OBE
