### ISSUE TITLE
Fontconfig error: Cannot load default config file when run xml2rfc on windows 10

### ISSUE THREAD

**Issue by Roc2Roc** [ietf-tools/xml2rfc#736]
I installed xml2rfc on windows 10 laptop by 'pip install xml2rfc'. Then run xml2rfc in powershell and get an error says "Fontconfig error: Cannot load default config file"

I installed it on another linux laptop and the command run smoothly.

Anyone can tell me what's the problem and how to fix it?

**Comment by kesara** [comment]
I haven't tried xml2rfc on Windows 10, but I was able to use it successfully on Windows 11 virtual machine.
I followed the following steps: https://notes.ietf.org/VzjJ-6FbQ-yXMo8mD0ToWw

Can you provide more details about what's your Python version and what's the `xml2rfc` version that `pip` tries to install?
A full error log from `pip install` will be more helpful.

**Comment by kesara** [comment]
Hope this issue is resolved. If not please reopen.
