### ISSUE TITLE
Missing bcp # in txt rendering #87

### ISSUE THREAD

**Issue by cabo** [ietf-tools/xml2rfc#742]
ietf-tools/xml2rfc#743

Suggested label: rendering issue

**Comment by kesara** [comment]
Project maintainers can transfer issues between GitHub projects.
I have transferred the original issue to xml2rfc.

**Comment by cabo** [comment]
Thank you!  How do I initiate such a transfer?

**Comment by kesara** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository
