### ISSUE TITLE
TXT generation fails while HTML and PDF succeed, error message is unhelpful

### ISSUE THREAD

**Issue by jgscudder** [ietf-tools/xml2rfc#765]
The attached XML fails to render as txt, with the unhelpful error message "xml2rfc error: text generation error". PDF and HTML succeed. I accept that there might be something wrong with the XML (which is quite old), but the error message doesn't help me figure out what it is.

For that matter, it would be nice to be able to see the more verbose errors-and-warnings form the old xml2rfc site offered.

P.S.: GitHub refused XML attachment, so I added a TXT extension to the attachment to circumvent that
[test.xml.txt](https://github.com/ietf-tools/ietf-at-ui/files/8584931/test.xml.txt)
.

**Comment by cabo** [comment]
Pagination code assumes there is a ToC (to which to insert page numbers).
You can still get .txt without ToC using --no-pagination

**Comment by jgscudder** [comment]
> Thanks for the bug report. In this case, `xml2rfc` crashed and failed to generate a meaningful error message. I'm transferring this issue to [xml2rfc](https://github.com/ietf-tools/xml2rfc).

Possibly it would be slightly more helpful to the user to expose the crash/stack trace information? Or at least instead of the very general "text generation error" (which could mean almost anything) say something more specific like "xml2rfc crashed"?

**Comment by kesara** [comment]
> > Thanks for the bug report. In this case, `xml2rfc` crashed and failed to generate a meaningful error message. I'm transferring this issue to [xml2rfc](https://github.com/ietf-tools/xml2rfc).
> 
> Possibly it would be slightly more helpful to the user to expose the crash/stack trace information? Or at least instead of the very general "text generation error" (which could mean almost anything) say something more specific like "xml2rfc crashed"?

Showing crash/stack trace in an online service can lead to security vulnerabilities [1].
Maybe author tools UI can be improved to provide a link to GitHub issues to open an issue on GitHub when such unexpected errors occurred?

1: [OWASP - Improper Error Handling](https://owasp.org/www-community/Improper_Error_Handling)

**Comment by cabo** [comment]
On 2. May 2022, at 00:55, Kesara Rathnayake ***@***.***> wrote:
> 
> 
> Thanks for the bug report. In this case, xml2rfc crashed and failed to generate a meaningful error message. I'm transferring this issue to xml2rfc.
> 
> Possibly it would be slightly more helpful to the user to expose the crash/stack trace information? Or at least instead of the very general "text generation error" (which could mean almost anything) say something more specific like "xml2rfc crashed"?
> 
> Showing crash/stack trace in an online service can lead to security vulnerabilities [1].
> Maybe author tools UI can be improved to provide a link to GitHub issues to open an issue on GitHub when such unexpected errors occurred?

But you have to preserve the relevant information — inputs and crash.
That could be done automatically (“the maintainers have been informed”) or via an option (proactive) or a button (reactive).

Grüße, Carsten

**Comment by kesara** [comment]
I've created https://github.com/ietf-tools/ietf-at-ui/issues/87 for author tools changes on error handling.
