### ISSUE TITLE
Beyond-ASCII characters in SVG get expanded to decimal character references

### ISSUE THREAD

**Issue by cabo** [ietf-tools/xml2rfc#767]
... and other weirdness.

Reduced example from an editors's copy of the jsonpath draft.
(as .xml.txt, duuh github.)

[jsonpath-reduced.xml.txt](https://github.com/ietf-tools/xml2rfc/files/8598028/jsonpath-reduced.xml.txt)

There are also error messages I don't understand:

``` 
jsonpath-reduced.xml(398): Warning: Unexpected text content after block tag: <{http://www.w3.org/2000/svg}tspan>〉
jsonpath-reduced.xml(400): Warning: Unexpected text content after block tag: <{http://www.w3.org/2000/svg}tspan>〉
jsonpath-reduced.xml(402): Warning: Unexpected text content after block tag: <{http://www.w3.org/2000/svg}tspan>〉
jsonpath-reduced.xml(398): Warning: Unexpected text content after block tag: <{http://www.w3.org/2000/svg}tspan>&#12297;
jsonpath-reduced.xml(400): Warning: Unexpected text content after block tag: <{http://www.w3.org/2000/svg}tspan>&#12297;
jsonpath-reduced.xml(402): Warning: Unexpected text content after block tag: <{http://www.w3.org/2000/svg}tspan>&#12297;
```

**Comment by cabo** [comment]
Here is the rendering.  The HTML looks as broken, but also has viewport issues I need to understand.

[jsonpath-reduced.pdf](https://github.com/ietf-tools/xml2rfc/files/8598037/jsonpath-reduced.pdf)

**Comment by cabo** [comment]
Bump.

**Comment by cabo** [comment]
While this bug is gone, have a look at the PDF renderings of my example please: there seem to be a few characters that cannot be shown in the PDF.  Is that a weasyprint font configuration issue?

**Comment by kesara** [comment]
I created #835 to capture the PDF rendering issue.

**Comment by kesara** [comment]
WeasyPrint 53.0+ seems to fix the issue with missing fonts.
But rendering isn't accurate in some cases.
Example: 
[jsonpath-reduced.pdf](https://github.com/ietf-tools/xml2rfc/files/9174407/jsonpath-reduced.pdf)
