### ISSUE TITLE
Docker image performance

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/xml2rfc#846]
Using run.sh is a useful way of doing development.  It's annoying that the image doesn't have git and a few basic tools, but once you get around that, the requirements are easily managed.

I do find it very frustrating that the build basically always runs the pip install from requirements.txt.  If the steps were reordered so that copying requirements.txt and installing from it came *before* a lot of the other copy commands, then it would be much faster to run in common cases.

**Comment by kesara** [comment]
I'll change the build order.

I can include more tools `git`.
May be `vim` as well.
Any other suggestions?

**Comment by martinthomson** [comment]
That would be great, thanks.  `less` is the other tool I found to be lacking.  It's not a big deal, but those three were all immediately missed.
