### ISSUE TITLE
RTL breakage in PDF

### ISSUE THREAD

**Issue by cabo** [ietf-tools/xml2rfc#873]
### Describe the issue

Archived-At: <https://mailarchive.ietf.org/arch/msg/auth48archive/_8ZjoHcPh5HfYxRQb3P4zVbdXUg>

  https://www.rfc-editor.org/authors/rfc9290.txt
  https://www.rfc-editor.org/authors/rfc9290.pdf
  https://www.rfc-editor.org/authors/rfc9290.html
  https://www.rfc-editor.org/authors/rfc9290.xml

This is likely to lead to TI state.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
This is an RTL support issue in WeasyPrint. I've created: https://github.com/Kozea/WeasyPrint/issues/1711
