### ISSUE TITLE
xml2rfc section nesting failure

### ISSUE THREAD

**Issue by klensin** [ietf-tools/xml2rfc#887]
### Describe the issue

In xml2rfc (at least 3.14.2), a nested <section> structure followed by  a paragraph associated with the outermost section, is reported as an error with an unexpected <t>.   Specifically (actual example extracted from an RFCXML document  below)

<section> ...
   <section> ... </section>
   <section> ... </section>
  <t> .... </t>
</section>

In the constructed example attached, the message 
"Error: Did not expect element t there, at /rfc/middle/section/t[2]"
is produced.

I understand that this particular construction may be confusing to read, but there are cases where it is important and, in any event, rules here should be a style and Style Guide issue, not imposed by the processor.

---- File extract -- (see separate report for why the complete file is not attached)
  <middle>  
    <section>
	   <name>top-level section</name>
	   <t> .... </t>
	   <section>
		  <name>subsection 1</name>
		  <t> --- 1 --- </t>
	   </section>
	   <section>
		  <name>subsection 2</name>
		  <t> --- 2 --- </t>
	   </section>
	   <t> Text belonging to the main, top-level, section</t>
	</section>
  </middle>
---------------

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
@klensin, The issue is the last `<t>` tag.
```
<t> Text belonging to the main, top-level, section</t> 
```
You can't have a `<t>` tag after `<section>` tag.
`section` schema is as follows: [name](https://ietf-tools.github.io/xml2rfc/#element-name)?, ( [artset](https://ietf-tools.github.io/xml2rfc/#element-artset) | [artwork](https://ietf-tools.github.io/xml2rfc/#element-artwork) | [aside](https://ietf-tools.github.io/xml2rfc/#element-aside) | [author](https://ietf-tools.github.io/xml2rfc/#element-author) | [blockquote](https://ietf-tools.github.io/xml2rfc/#element-blockquote) | [contact](https://ietf-tools.github.io/xml2rfc/#element-contact) | [dl](https://ietf-tools.github.io/xml2rfc/#element-dl) | [figure](https://ietf-tools.github.io/xml2rfc/#element-figure) | [iref](https://ietf-tools.github.io/xml2rfc/#element-iref) | [ol](https://ietf-tools.github.io/xml2rfc/#element-ol) | [sourcecode](https://ietf-tools.github.io/xml2rfc/#element-sourcecode) | [t](https://ietf-tools.github.io/xml2rfc/#element-t) | [table](https://ietf-tools.github.io/xml2rfc/#element-table) | [ul](https://ietf-tools.github.io/xml2rfc/#element-ul) )\*, [section](https://ietf-tools.github.io/xml2rfc/#element-section)\*

Reference:
* https://ietf-tools.github.io/xml2rfc/#section-2.50
* https://www.rfc-editor.org/rfc/rfc7991.html#section-2.46

Original XML (for easy reading):
```
  <middle>
    <section>
      <name>top-level section</name>
      <t> .... </t>
      <section>
        <name>subsection 1</name>
        <t> --- 1 --- </t>
      </section>
      <section>
        <name>subsection 2</name>
        <t> --- 2 --- </t>
      </section>
      <t> Text belonging to the main, top-level, section</t>
    </section>
  </middle>
```

**Comment by cabo** [comment]
And that limitation in the grammar is not just foolery -- the traditional section nesting system we are all used to does not allow to return to a higher-level section once a lower-level one has been opened.  The boundary between sections is expressed using headings, and there is no heading that could be used to go up (except starting a new higher-level section).   And, what would be the section number of that paragraph at the end?

**Comment by jrlevine** [comment]
This is as specified in RFC 7991, not a bug

**Comment by klensin** [comment]
I'll figure out how to adjust the document in question, but several comments in no particular order:

  (1)  Like it or not, that construction has appeared in RFCs for decades.  The actual document in which I encountered the problem goes back more than 20 years (can't remember whether it was written for xml2rfc v2 or v2) and the uneven nested construction was possible (and used) in the RFC Editor's nroff constructions of the late 1980s if not earlier. 

 (2) If the concern is that the end of a set of nested sections cannot be distinguished from the one in which they are embedded, there are all sorts of  ways to lay out a document to make that easy.   In particular, I note that 

    foo-text
       * bar-text1
       * bar-text2
       * bar-text3
    more foo-text

((Above written so that "more" appears immediately under "* bar-text3" and is aligned under "foo" and  the "* bar" lines are aligned vertically and  indented a bit in all three cases,))

has never been seen as an issue but 

  N.     foo-text
      N.1  bar-text1
      N.2  bar-text2
      N.3  bar-text3
   more foo-text 

((Above written so that "more" is aligned under "N. foo" and the "N.x  bar" lines are aligned vertically and indented a bit in all three cases.   This tool apparently will not allow that construction.)

Is a horrible problem that cannot be understood.  Whether one agrees that the second construction is a good idea or not (fwiw, as I more or less said earlier, in the overwhelming number of cases, I don't, but I see exceptions) I hope the parallelism (and formatting possibility if needed) is at least clear.  

 (3) I am having, at best, some small difficulty understanding why 7991 seems to be treated as, AFAICT, nearly holy writ when people on this list (or a subset of them) like what it has to say but can be quietly ignored or changed in substantive ways, without consulting the broader community, when they don't or it proves inconvenient.

(4) For decades going back to the 1970s, constructions like this were considered "at the discretion of the author" as long as the formatting that was produced did not appear problematic (on a case by case basis) to the RFC Editor.  If it did, there was a discussion in which the RFC Editor nearly always (but not always) won.    We seem to be replacing that rather flexible model with a set of rules that are far more rigid that anything I've experienced working with technical publishers.  I don't think  the community consciously signed up for that as an intended consequence of the xml2rfc v3 definition (or anything else).  For similar reasons, while we had two generations of "Instructions to RFC Authors" (some not published as RFCs), when we switched to Style Guides, that it what they were called, not "Style Dicta",  "Style Binding Rules", or even "Style Instructions".

**Comment by jrlevine** [comment]
It looks like you may be conflating sections and lists.  Sections are not indented, they're just numbered. Lists are indented and have a different grammar. In a text rendered document the only indication of the end of a section is the heading of the next section. In the HTML there is a </section> tag but it doesn't display as anything or change the indent.
The XML grammar has been this way since 2016 and  I don't see how you could even indicate that a paragraph didn't belong to the same section as its predecessor in the old nroff. I am pretty sure this is the first time anyone has asked about it in the XML grammar.

**Comment by klensin** [comment]
Not exactly and therein lies the point.    The decision as to
how to format/present sections or lists is a presentation (page
layout) matter, not a markup one. I have, for example, seen more
than a few publications that indent the bullets of bullet lists
slightly and then use handing indent for more than one line of
text but that treat numbered lists almost like sections with
numbers aligned with the section text and sometimes aligning the
numbers and the lines of text that follows rather than hanging
the number and indenting the rest.  Such numbered lists can be
distinguished from sections only because the section numbers are
associated with headers/titles while numbered lists use list
text on the same line as the number.    

FWIW, note also that, in general, a numbered list can be
indistinguishable (in presentation form) from numbered
paragraphs only when those list items consist of no more than
one paragraph each).    And I'm certainly seen subsections
indented or set in different type (smaller or different font)
than the main sections.

These are all layout/design choices, not the rigid and immutable
formatting/layout rule that you and Carsten seem to assume.

As I said, I'll make the relevant document conform -- this is,
IMO, not worth anyone coming to blows over.  But I think some
more serious thought about how we are making stylistic rules and
how rigid we want to be about them is in order (as usual,
probably on the RSWG list rather than here).

    john


--On Monday, September 5, 2022 13:53 -0700 John L

**Comment by cabo** [comment]
On 2022-09-05, at 23:26, klensin ***@***.***> wrote:
> 
> These are all layout/design choices, not the rigid and immutable
> formatting/layout rule that you and Carsten seem to assume.

I wasn’t talking about formatting/layout as much as about the logical categories that we make available as vocabulary.

The split between a section structure and a (numbered) nested list structure occurred a long time ago; for the last 40 years, we have been assuming that (simplified)

section = heading *para *section

The ways available for presenting (formatting) this structure in formatting certainly was one motivation; the other was that there are certain assumptions authors (and readers!) have about section numbering and cross-references to sections that essentially require this structure.

Of course, markdown doesn’t have this structure, so the conversion I had to implement from markdown’s leveled headings to a section structure is one thing that makes me interested in this subject.

I’m curious which document you found that goes beyond this traditional section structure.

Grüße, Carsten
