### ISSUE TITLE
xml2rfc doesn't add published date when ipr attribute is none

### ISSUE THREAD

**Issue by kesara** [ietf-tools/xml2rfc#893]
### Describe the issue

`xml2rfc` doesn't add the published date on HTML & PDF outputs when `ipr` attribute is not set or set to `none`.
When `ipr` attribute is not set, `xml2rfc` should still add the published date on HTML & PDF outputs.

References:
* https://github.com/ietf-tools/xml2rfc/blob/main/xml2rfc/writers/html.py#L1660
* https://mailarchive.ietf.org/arch/msg/tools-discuss/9eh_DjQhhYW2_XaX8avmyzwg3R8/

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by selfissued** [comment]
Any ETA for fixing this bug?  A bunch of OpenID specs are being published without dates at present. :-(  Thanks!

**Comment by kesara** [comment]
@selfissued, the fix has been merged to the main branch. This fix will be on the next xml2rfc release, scheduled to release today.
