### ISSUE TITLE
add submissionType for Editorial stream and SoTM in output

### ISSUE THREAD

**Issue by alicerusso** [ietf-tools/xml2rfc#896]
### Description

Please add a new submissionType value for the Editorial stream (created by RFC 9280).

For "Status of This Memo" content when rendering an RFC, please see item 25 ("Editorial Stream Informational") on this page:  https://www.rfc-editor.org/materials/status-memos.txt
which is the outcome of [S6.3 of RFC 9280](https://www.rfc-editor.org/rfc/rfc9280.html#section-6.3).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ronaldtse** [comment]
This will also be relevant to the bibxml-service when enacted.

**Comment by paulehoffman** [comment]
Here is an additional nudge for this simple addition. I am being blocked from submitting a draft in the Editorial stream because of this.

**Comment by rjsparks** [comment]
Has a draft been adopted by the RSWG? If not, why would you need to indicate editorial stream in the document at this time? 

In any case, this will be a high priority, but because of vacations it will be next week at the earliest.

**Comment by rjsparks** [comment]
(There is also a lot of work underway to build out the parts of the datatracker that would let the RSWG adopt a document, request publication, and track RSAB approval).

**Comment by paulehoffman** [comment]
> Has a draft been adopted by the RSWG? If not, why would you need to indicate editorial stream in the document at this time?

I wanted to be sure that it *could* be adopted before I suggest to the WG that it should be.
