### ISSUE TITLE
Delete all fonts before installing required fonts in Docker images

### ISSUE THREAD

**Issue by kesara** [ietf-tools/xml2rfc#904]
### Describe the issue

Delete all OS fonts before installing the required fonts in the Docker images to avoid fonts leaking in PDF files.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jrlevine** [comment]
This is a reasonable fix in the short term but since a lot of us run xml2rfc on our regular PCs, I hope we can figure out how fonts are leaking into Weasyprint and fix it.

**Comment by kesara** [comment]
@jrlevine I agree the proper fix is to avoid this scenario. I'm closing this issue in favour of #905 & #906.

There can be other instances of font leakages, I guess we have to analyze the fonts in PDF files before publication to find those issues.
