### ISSUE TITLE
No top margin for <dl> & <p> in a <ul>

### ISSUE THREAD

**Issue by kesara** [ietf-tools/xml2rfc#936]
### Describe the issue

From @alicerusso (https://github.com/ietf-tools/xml2rfc/issues/674#issuecomment-1310261095):

...
missing a blank line between the output of `<t>` and `<dl>` (nested within a `<ul>`) in the HTML and PDF. (The TXT file is OK.)

https://www.rfc-editor.org/v3test/test9336.html#section-4
https://www.rfc-editor.org/v3test/test9336.pdf#section-4
(for comparison: https://www.rfc-editor.org/v3test/test9336.txt)
source: https://www.rfc-editor.org/v3test/test9336.xml

i.e., a missing blank line above "Excluded KeyPurposeId procedure:" 

This affects readability esp. in the PDF where there happens to be a page break after the first `<dt>`.

screenshot of HTML:
<img width="658" alt="9336" src="https://user-images.githubusercontent.com/40246629/201099164-094b3e5c-e2ce-43e6-9797-3e9ad64e106b.png">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
This is caused by the following fix: https://github.com/ietf-tools/xml2rfc/commit/fa224c8c386941ed96678dbd790963d7f7681235

**Comment by rvanrheeenen** [comment]
FYI that we see an oddity in the PDF that does not appear in the HTML or TXT.

When `<dl newline="false">` is used in Section 4, the first list item in the PDF seems to incorrectly use newline="true" formatting while the second list item is correctly formatted with newline="false". This does not happen in the HTML or TXT.

However, when `<dl newline="true">` is used in Section 4, both list items are correctly formatted in all three output formats.

(We decided to use `<dl newline="true">` in this document, but we wanted to mention the oddity when using `<dl newline="false">`.)


PDF with `<dl newline="false">` - contains oddity:
https://www.rfc-editor.org/v3test/test9336-newline-false.pdf#section-4

For comparison, HTML with `<dl newline="false">`: 
https://www.rfc-editor.org/v3test/test9336-newline-false.html#section-4

XML source with `<dl newline="false">`:
https://www.rfc-editor.org/v3test/test9336-newline-false.xml

PDF with `<dl newline="true">`:
https://www.rfc-editor.org/v3test/test9336-newline-true.pdf#section-4

XML source with `<dl newline="true">`:
https://www.rfc-editor.org/v3test/test9336-newline-true.xml

**Comment by kesara** [comment]
I don't think this issue (#936) is related to this issue.
But the reason why `<dl newline="false">` is not rending correctly in the PDF file is this happens near a page break.
Seems like one of the edge cases.
I've created #946 for this.
