### ISSUE TITLE
IETF author tools: undefined with create a .txt file. The HTML works fine.

### ISSUE THREAD

**Issue by bclaise** [ietf-tools/xml2rfc#967]
### Describe the issue

Weirdly, I only have this issue (can't generate a txt from xml) only from my VM in virtualbox and only for .txt (HTML generation works fine)
Probably not a bug but an environmental issue.
Any help appreciated. Low priority I guess

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cabo** [comment]
Do you have an error message?

**Comment by bclaise** [comment]
@cabo.
For the record, I received "undefined" as an error message.
And I finally discovered the issue. I had to exit my VPN (to be able to load the file, I guess). What's weird is that it worked fine with HTML.
