### ISSUE TITLE
Latin, non-ascii initials

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/xml2rfc#996]
### Describe the issue

https://datatracker.ietf.org/doc/html/draft-ietf-opsec-probe-attribution renders the first author, Éric, with an E and not an É.

There seems to be some sort of transliteration going on here, but that is probably unnecessary.

This issue might be moot if we move to including names in full, as we should.  However, if we do nothing about that, then fixing this might help.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cabo** [comment]
> ### Describe the issue
> https://datatracker.ietf.org/doc/html/draft-ietf-opsec-probe-attribution renders the first author, Éric, with an E and not an É.

As requested by the authors:

``` 
author:
 -
    ins: E. Vyncke
    name: Éric Vyncke
``` 

```
    <author initials="E." surname="Vyncke" fullname="Éric Vyncke">
```

Fix needed in document source.

**Comment by rjsparks** [comment]
Closing this as not an xml2rfc issue.
